"""Checkup and Check

Revision ID: 8056a3ff2a0a
Revises: 83b69f811e6d
Create Date: 2025-01-13 22:43:33.644794

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8056a3ff2a0a'
down_revision: Union[str, None] = '83b69f811e6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkups',
    sa.Column('checkup_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
        sa.PrimaryKeyConstraint('checkup_id')
    )

    op.create_table('checks',
    sa.Column('check_id', sa.Integer(), nullable=False),
        sa.Column('check_type', sa.Enum('COOKIE', 'LIGHTHOUSE', 'NETWORK', 'SCAN_PORTS', 'TECHNOLOGIES', name='checktype'), nullable=False),
        sa.Column('status', sa.Enum('CREATED', 'RUNNING', 'COMPLETED', 'FAILED', name='checkstatus'), nullable=False),
        sa.Column('results', sa.JSON(), nullable=True),
        sa.Column('checkup_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['checkup_id'], ['checkups.checkup_id'], ),
        sa.PrimaryKeyConstraint('check_id')
    )
    op.add_column('chats', sa.Column('check_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chats', 'checks', ['check_id'], ['check_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'check_id')
    op.drop_table('checks')
    op.drop_table('checkups')
    # ### end Alembic commands ###
