"""Chat and Messages

Revision ID: 83b69f811e6d
Revises: c856712ab4de
Create Date: 2025-01-08 03:46:05.621197

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '83b69f811e6d'
down_revision: Union[str, None] = 'c856712ab4de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
                    sa.Column('chat_id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('chat_id'),
    )

    op.create_table('messages',
                    sa.Column('message_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"),
                              nullable=False),
                    sa.Column('content', sa.String(), nullable=False),
                    sa.Column('attachment_url', sa.String(), nullable=True),
                    sa.Column('sender_type', sa.Enum('USER', 'SYSTEM', 'ASSISTANT', name='sendertype'), nullable=False),
                    sa.Column('chat_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ),
                    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('chats')
    # ### end Alembic commands ###
